### ISSUE TITLE
Several error in codebase

### ISSUE THREAD

**Issue by jshilong** [kkhoot/PAA#1]
Hi, Thanks for your great work,
I scan the code, and found several obviously errors,
such as 
https://github.com/kkhoot/PAA/blob/6c0d6c71f2c2eb858acda72fab18a417c6895076/paa_core/modeling/rpn/paa/loss.py#L267
smoothl1loss not import 
and in config 
https://github.com/kkhoot/PAA/blob/6c0d6c71f2c2eb858acda72fab18a417c6895076/configs/paa/paa_R_50_FPN_1x.yaml#L21
USE_IOU_PRED is defined b twice.
Did you test the code before release ?

**Comment by kkhoot** [comment]
Hi, thanks for pointing this out!
Let me fix those error. BTW the code as is runs without trouble, since the smooth_l1_loss is actually not being used and the default loss for localization is GIoU loss. Anyway, thanks for reporting this!

**Comment by kkhoot** [comment]
Fixes have been applied. Thanks again and please let me know if you have any trouble in running the code.
