### ISSUE TITLE
mAP is a little different when testing with batch_size = 1

### ISSUE THREAD

**Issue by feiyuhuahuo** [kkhoot/PAA#11]
Hi,
I found that the mAP is 41.0 when testing with batch_size = 1? With batch_size=2 and 4, I can get 41.1 mAP. The config is res50_1.5x.
![paa_410](https://user-images.githubusercontent.com/32631344/91549732-f3363a80-e959-11ea-9aec-a0a742b0fa1c.png)
Do you know why?
Thanks for the reply.

**Comment by kkhoot** [comment]
Hi @feiyuhuahuo , It is probably because different batch sizes cause different input padding for input images. The same image with different boundary padding can produce slightly different outputs near the padded region of the image.
