### ISSUE TITLE
Warmup scheduler seems not working?

### ISSUE THREAD

**Issue by feiyuhuahuo** [kkhoot/PAA#12]
Hi
In the supplementary material in your paper, you used warmup in the first 500 iterations. But I found that the learning rate keeps the same when training.
![image](https://user-images.githubusercontent.com/32631344/91807821-ef0e6380-ec5e-11ea-8a0f-15ea378d1b58.png)
The `warmup_method` in your config is 'constant', don't you think it should be 'linear'?

**Comment by kkhoot** [comment]
Hi, the constant warmup assigns a smaller LR (1/3 of the original LR) for the first 500 iterations. I think the linear warmup should also be working well. I don't think the choice between constant and linear warmup will make a big difference here.
