### ISSUE TITLE
How much influence do the trainable scalars in the regression head have?

### ISSUE THREAD

**Issue by feiyuhuahuo** [kkhoot/PAA#15]
Seems there are not such scalars in other object detectors. Did you do any ablation study on this factor? Would the performance be influenced heavily if these scalars are removed?

**Comment by kkhoot** [comment]
It was actually introduced in FCOS, and according to the ATSS paper using the scalar layers gives 0.2 AP improvements. We used the same architecture as FCOS and ATSS for a comparison purpose.
