### ISSUE TITLE
A question about Ablation

### ISSUE THREAD

**Issue by LaoYang1994** [kkhoot/PAA#2]
I am not quite clear about the settings of you baseline in the right table of Table1. Is that the same setting (only one anchor + assignment strategy similar to RetinaNet) like the first line in Table 3 of ATSS?

**Comment by kkhoot** [comment]
Hi, thanks for the question. The first row of the right table of Table 1 (34.6 AP) is the modified RetinaNet with a single anchor used in FCOS and ATSS (i.e. RetinaNet with GroupNorm, Scalar layers in the feature towers) with GIoU loss. I think this can be compared with the model in Table 1 of ATSS without the "In GT Box" and "Centerness". Hope this helps.

**Comment by LaoYang1994** [comment]
@kkhoot OK, I see. Thanks for your reply. Good job!
