### ISSUE TITLE
coco test-dev 2017

### ISSUE THREAD

**Issue by Markovcom** [kkhoot/PAA#20]
Hello, thank you for your nice work. I test the coco test-dev with your code, and then upload the bbox.json to the coco evaluation server. I meet the follow issues:
![image](https://user-images.githubusercontent.com/26458922/96973880-11c84480-154b-11eb-8b8e-0de251fbf71d.png)

**Comment by kkhoot** [comment]
Hi, thanks for your interest!
Did you zip the bbox.json with directory names? In my experience, the server failed to load the zip file when the zip contains directory names which was specific to my system. If this is your case, then please remove them and retry.

**Comment by Markovcom** [comment]
Thank you very much, i solve it with your suggestion.
