### ISSUE TITLE
Pretrained Models.

### ISSUE THREAD

**Issue by Joker316701882** [kkhoot/PAA#21]
Hi. @kkhoot 

Sorry for bothering you. We would like to cite your work in our work and run some extra tests on PAA. Is it possible for you to upload the following pre-trained models?

1). PAA_X_101_64x4d_FPN_2x
2). PAA_dcnv2_X_101_64x4d_FPN_2x

Bests!

**Comment by kkhoot** [comment]
Hi @Joker316701882 , I don't have those models, so I need to train them again. When is your due date for submission?

**Comment by Joker316701882** [comment]
@kkhoot 
No worry. I already start to train these two models with your code! Thank you for your kind reply : )

**Comment by kkhoot** [comment]
Great that you are able to train them yourself! Sorry for this inconvenience though.

**Comment by kkhoot** [comment]
@Joker316701882 JFYI I trained PAA_X_101_64x4d_FPN_2x and added the model link on READEM.md. This models shows 46.4 mAP on COCO val and 46.8 mAP on test-dev. Hope this helps.

**Comment by Joker316701882** [comment]
@kkhoot 
Thank you very much!

**Comment by kkhoot** [comment]
@Joker316701882 PAA_dcnv2_X_101_64x4d_FPN_2x model link also has been updated. It shows 48.8 (val) and 49.2 (test-dev).
