### ISSUE TITLE
question about FNP

### ISSUE THREAD

**Issue by lji72** [kkhoot/PAA#23]
"We also compare our method with
two simpler methods, namely fixed numbers of positives (FNP) and fixed positive
score ranges (FSR). FNP defines a pre-defined number of top-scoring samples "  was written in paper.  what does top-scoring mean?  it means combine loss, or iou-score or cls-score, which one is true used in paper ? 
Thanks advance for your reply.

**Comment by kkhoot** [comment]
Hi, thanks for your interest.
It means the combined score in Eq. 1 in the paper and was implemented as selecting anchors of top-k smallest loss values. Hope this helps.

**Comment by lji72** [comment]
Thanks for your reply.
