### ISSUE TITLE
Have you tried other IoU threshold?

### ISSUE THREAD

**Issue by feiyuhuahuo** [kkhoot/PAA#24]
https://github.com/kkhoot/PAA/blob/13d5721786a6aa3d3701d44a6d1216377c007a74/paa_core/config/defaults.py#L312
Noticed that the IoU threshold in PAA is 0.1, which I think is for high recall. Have you tried other value, and what's the effect?

**Comment by kkhoot** [comment]
Hi @feiyuhuahuo , In my implementation, the IoU threshold determines a group of candidate positive anchors on which anchor scores are calculated for a certain GT object. Anchors whose IoU is below this threshold is considered as negative samples without calculating their anchor scores. This means that some anchors with lower IoU may miss a chance to be assigned as positive samples when they could get high scores.
I don't remember the exact amount of difference, but IOU_THRESHOLD=0.5 was about 0.3 mAP worse than IOU_THRESHOLD=0.1 if I remember correctly. This means that there are (not many but certainly) high-scoring anchors whose IoU is low, and they can be more appropriate as positive samples than anchors of higher IoU.
