### ISSUE TITLE
Is it possible to use this algorithm in an anchor-free network

### ISSUE THREAD

**Issue by linsy-ai** [kkhoot/PAA#26]
Is it possible to use this algorithm in an anchor-free network such as FCOS? Thank you very much!

**Comment by kkhoot** [comment]
Hi @linsy-ai , PAA should be applicable to FCOS or any other anchor-free detectors, just like ATSS does. Although this codebase doesn't support it as-is, you can change [this anchor-based assignment function](https://github.com/kkhoot/PAA/blob/13d5721786a6aa3d3701d44a6d1216377c007a74/paa_core/modeling/rpn/paa/loss.py#L89) to whatever assignment logic you want. I anticipate the performance will be similar to the current anchor-based assignment, as ATSS and other dynamic assignment algorithms show almost the same performance for both anchor-based and anchor-free models.

**Comment by linsy-ai** [comment]
Thank you very much for your reply and your good work, and I want to know how this eccv2020_fig1.jpg picture is drawn?

https://github.com/kkhoot/PAA/blob/master/eccv2020_fig1.jpg
Thank you again for your  reply！

**Comment by kkhoot** [comment]
It is a drawing using MS Office :)

**Comment by linsy-ai** [comment]
Thank you very much
