### ISSUE TITLE
Loss weight

### ISSUE THREAD

**Issue by YangHai-1218** [kkhoot/PAA#27]
Hi, thanks for your work. But I wonder if the result is sensitive to the loss weight (1.0, 1.3, 0.5). As we know, in ATSS, the loss weight is (1.0, 2.0, 1.0) and in FCOS, the loss weight is (1.0, 1.0, 1.0). Have you tried other loss weight combinations？ Thanks!

**Comment by kkhoot** [comment]
Hi @NaCl-Ocean , thank you for your interest. The loss weights were set to make the magnitudes of the three losses similar when they are converged. I also tested the weights (1.0, 1.0, 1.0), and I don't remember exactly but the results on Res50 were similar. There may be better loss weights that would give better results, but I don't think it significantly affects the model performance.

**Comment by YangHai-1218** [comment]
Thanks for your reply. I tested (1.0, 2.0, 1.0)(ATSS) loss weight on PAA Res50 by mmdetection, and got 40.1 mAP. Maybe the loss weight will slightly affect the model performance. It may also due to be unstable performance under 1x setting.

**Comment by kkhoot** [comment]
Thank you for sharing your result. Yes I think you are right. The loss weights can slightly affect the model performance (if not, we don't need to set the weights :)). It is also correct that the 1x setting doesn't make the training converged, so there are fluctuations in the results.
