### ISSUE TITLE
multi-scale testing

### ISSUE THREAD

**Issue by jianpursuit** [kkhoot/PAA#29]
What scales did you use in the multi-scale testing? Thanks!

**Comment by kkhoot** [comment]
Hi @jianpursuit , sorry for this late response. Please check the below line:
https://github.com/kkhoot/PAA/blob/13d5721786a6aa3d3701d44a6d1216377c007a74/configs/paa/paa_dcnv2_X_101_64x4d_FPN_2x.yaml#L53
