### ISSUE TITLE
Fluctuation range of r50 1x.

### ISSUE THREAD

**Issue by jshilong** [kkhoot/PAA#3]
Hi, I get mAP 40.4 of paa-res50 with pytorch 1.3, is it in normal fluction range of paa ?

**Comment by kkhoot** [comment]
Hi, I actually tried R50_1x setting only once, so not sure about the performance fluctuation. What is clear is that 1x setting (90k iterations) does not make the training fully converged, which was the reason why I used 135k setting for ablation in the paper. You can check the fluctuation of a model's performance by using the argument --eval_dir [/path/to/checkpoint/dir] for test_net.py. This will sequentially perform testing for all checkpoints in the dir:
https://github.com/kkhoot/PAA/blob/master/tools/test_net.py#L164-L165

**Comment by jshilong** [comment]
Thanks for your reply, I will try it.

**Comment by Joker316701882** [comment]
@jshilong 
Hi, have you tried to test PPA 1x without Score Voting? I think score voting is a common trick that other methods(ATSS, FCOS) can easily apply it. So I'm curious how much gain the PAA can achieve without score voting under the 1x setting over ATSS.
