### ISSUE TITLE
Paper Link

### ISSUE THREAD

**Issue by luuuyi** [kkhoot/PAA#4]
Execuse me. Could you share your paper link? THX.

**Comment by kai-xl8** [comment]
Hi, thanks for your attention. The link is below:
https://arxiv.org/abs/2007.08103
I will also update README. Thanks.

**Comment by kkhoot** [comment]
Hi, thanks for your attention. The link is below:
https://arxiv.org/abs/2007.08103
I will also update README. Thanks.

**Comment by luuuyi** [comment]
@kkhoot ok, THX
