### ISSUE TITLE
Seems a bug when computing paa?

### ISSUE THREAD

**Issue by jshilong** [kkhoot/PAA#8]
The code about computing paa confused me，
https://github.com/kkhoot/PAA/blob/1d940f2cdd08b47cfe829cbdaae69a5633ccc463/paa_core/modeling/rpn/paa/loss.py#L221
 seems should change to  `is_neg = inds[bg_max_idx:]`

**Comment by kkhoot** [comment]
Oh my bad. You are right. The current code should be working like something in between fig.3 (c) and (d)... I will fix it. Thanks!

**Comment by jshilong** [comment]
Sure, I believe fig b not the best, because when two peak depart away, There are lots of ignore samples which may weaken model's ability to distinguish pos samples and neg samples, and I confirm it by running real fig.b and get mAP 39.8.
And I agree that current code should be working like something in between fig.3 (c) and (d), I am running fig.c now.

But this error does not affect the main contribution of your paper, hope you can fix  it asap and do correct ablation study again in camera-ready version.

**Comment by kkhoot** [comment]
Thanks for sharing your result. I am not sure if I can update the camera-ready version since the deadline has already passed. Will update the arXiv version with the correct test soon.

**Comment by Xudangliatiger** [comment]
Find the same bug……when this sampling method is used in training，the num_neg + num_pos > num_all. 

And the original code should be the Fig. 3 (c).
